### ISSUE TITLE
登録フォーム追加　「個人情報保護方針(プライバシー ポリシー)」

### ISSUE THREAD

**Issue by scottmacdonald1** [cloudopsdays/dreamkast#34]
登録フォームの最後に以下追加可能でしょうか？

個人情報保護方針(プライバシー ポリシー)* （必須）

主催者の提示する [個人情報保護方針(プライバシー ポリシー)](https://event.cloudopsdays.com/codt2021/privacy) をご確認のうえ、ご同意いただき お申し込みを確定してください。
    □ 同意する （チャックボックスもしくはプルダウン）

**Comment by jacopen** [comment]
対応しますね
