### ISSUE TITLE
CODTのDkを外形監視する

### ISSUE THREAD

**Issue by jacopen** [cloudopsdays/dreamkast#46]
CloudWatchから外形監視して問題があったらSlackに通知するようにする。アカウントはGAFA側のを使う

https://event.cloudopsdays.com/codt2021/registration

**Comment by ShotaKitazawa** [comment]
だん
https://ap-northeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-1#synthetics:canary/detail/codt2021

**Comment by jacopen** [comment]
正常動作確認できているのでこちら閉じます！
