### ISSUE TITLE
Permalinkページからセッション登録できるようにする

### ISSUE THREAD

**Issue by jacopen** [cloudopsdays/dreamkast#60]
https://cloudopsdays.slack.com/archives/CQJ6YCA3H/p1623888641120900

```
Twitterからの登録者を増やそうとするために、Permalinkで開いた後のページに「セッションを登録する」ボタンがあったら、導線として嬉しかったりするのかなと思いましたが、いかがでしょう？
今はPermalinkで開いた後「Login」か、「セッション一覧」、「Topページ」しか導線がない感じです。
```

**Comment by jacopen** [comment]
こちらは実装をチャレンジしてみたのですが現在の構成だと思ったより手間がかかってしまうため、代案として未登録者に登録を促すための説明文およびリンクを追加する形で考えています

**Comment by scottmacdonald1** [comment]
チャレンジをありがとうございました。説明文およびリンクの対応で良いと思います。
