### ISSUE TITLE
スポンサー追加

### ISSUE THREAD

**Issue by scottmacdonald1** [cloudopsdays/dreamkast#62]
- Platinum  1社追加
PagerDuty

- Gold   2社追加
Datadog, Inc.
OpenInfra Foundation

**Comment by jacopen** [comment]
PagerDutyは #49 DataDogは #47 で既に依頼を受けていたので対応済みです。

**Comment by jacopen** [comment]
OpenInfra Foundationのロゴはありますか？ @scottmacdonald1

**Comment by miyamotoc** [comment]
![OpenInfrastructureFoundation_300x86_透過](https://user-images.githubusercontent.com/82624753/125214611-f24c9400-e2f2-11eb-9e6a-349dc10e4066.png)
こちらでお願いいたします。
