### ISSUE TITLE
セッション動画の公開設定について

### ISSUE THREAD

**Issue by miyamotoc** [cloudopsdays/dreamkast#63]
管理画面＞Talksより各セッションのVimeo IDを入力しOn Airにすればよいと認識していましたが、表から見ると動画が表示されません。

また、7月14日公開ですが、手動で全部をOn Airにしていかないとだめでしょうか。

**Comment by jacopen** [comment]
@miyamotoc 
On Airステータスは8/27のライブイベントでは使用しますが、7/14のアーカイブ公開の際には使用しませんので、そこは変更する必要はありません。

#55 で進めている実装が入ると、イベント全体のステータスを『アーカイブ公開モード』に切り替えることで、設定していただいたVimeoが表にどばっと公開されるという仕組みです。この切り替えを7/14に１回行うだけで全ての動画が表示されるようになります

**Comment by miyamotoc** [comment]
@jacopen ありがとうございます。それでは実装を待ち、設定を行いたいと思います。よろしくお願い申し上げます。

**Comment by scottmacdonald1** [comment]
@jacopen  

[archived] モードで動画が表示されること確認しました。
確認ですが、[archived] モードではブースのリンクが表示されないです。
[video_enabled]モードではブースのヘッダーリンクとpermalink ページにブースロゴも表示されます。

オンデマンド配信中の本番用は[video_enabled]モードでしょうか？

因みに[archived] モードでも[video_enabled]モードでもtwitter のフィードがなくなりますが、これは仕様でしょうか？

**Comment by jacopen** [comment]
@scottmacdonald1 
はい、 オンデマンド配信中は video_enabled モードでの運用になります。
archivedモードはCNDT向けのが残っている状態で、恐らくCODTでは使わないかな、と思っています。

Twitterのフィードに関しては、コンテンツ表示部分を広く取ろうとするとどうしても邪魔になってしまうために外してしまっています。
もしやっぱりTwitterフィードがあったほうがいいという場合は、ページ下部に挿入という形で復活も可能です

**Comment by jacopen** [comment]
@scottmacdonald1 
はい、 オンデマンド配信中は video_enabled モードでの運用になります。
archivedモードはCNDT向けのが残っている状態で、恐らくCODTでは使わないかな、と思っています。

Twitterのフィードに関しては、コンテンツ表示部分を広く取ろうとするとどうしても邪魔になってしまうために外してしまっています。
もしやっぱりTwitterフィードがあったほうがいいという場合は、ページ下部に挿入という形で復活も可能です

**Comment by scottmacdonald1** [comment]
承知しました。ページ下部でtwitter feedを復活いただけますでしょうか。
