### ISSUE TITLE
バーチャルブースの資料埋め込み最大件数について

### ISSUE THREAD

**Issue by miyamotoc** [cloudopsdays/dreamkast#73]
ブースの動画の埋め込み「Booth: Vimeo
Vimeo embed url」ですが、pdfと同様複数点の動画を埋め込む対応は可能でしょうか。複数社は3点の動画掲載を希望されています。また、PDF資料は現在最大3つしか入れられないようですが、6つまで増やすことは可能でしょうか。

**Comment by jacopen** [comment]
ちょっと修正可能か検討しますね。これお急ぎで必要そうですか

**Comment by miyamotoc** [comment]
急ぎではないですが難しい場合は、スポンサーへその旨ご案内しますので、お知らせください。
