### ISSUE TITLE
dashboard　スポンサーロゴ順番・内容

### ISSUE THREAD

**Issue by scottmacdonald1** [cloudopsdays/dreamkast#75]
表示順番はスポンサーレベル順のままで変更可能でしょうか。
https://event.cloudopsdays.com/codt2021/admin/sponsors

また、Gold にOpenInfra Foundation の反映はまだですね？

**Comment by jacopen** [comment]
ここの表示順番という意味であってますか？
![image](https://user-images.githubusercontent.com/79102/125253509-75420e80-e334-11eb-82f8-548e1491d819.png)

OpenInfraについては今日ロゴをいただいたので、修正版のリリースは今晩から明日朝ごろに行われる予定です

**Comment by scottmacdonald1** [comment]
そうです。OpenInfraは了解です。
