### ISSUE TITLE
資料URL

### ISSUE THREAD

**Issue by scottmacdonald1** [cloudopsdays/dreamkast#76]
https://event.cloudopsdays.com/codt2021/admin/speakers/1/edit　など
セッション情報の「資料URL」リンクを試しに入れたが、表示されないようです。
実装の現状では資料表示はできないでしょうか

**Comment by jacopen** [comment]
@scottmacdonald1 今回はセッション情報はセッションデータCSVから登録する形で利用されていますので、セッションデータのSpreadsheetのdocument_urlに講演資料URLを入れて、管理画面からTalksの登録をすると表示されます

![image](https://user-images.githubusercontent.com/79102/125279750-44bb9e00-e34f-11eb-9651-3337b6dcf009.png)
