### ISSUE TITLE
ブースTOPページのロゴ統一

### ISSUE THREAD

**Issue by miyamotoc** [cloudopsdays/dreamkast#82]
![ブース](https://user-images.githubusercontent.com/82624753/125373160-93a11c00-e3bf-11eb-8527-0dd8966d3593.png)
ブースTOPページのロゴが白背景とそうでないもので統一されていないので、恐れ入りますが、修正をお願いできますでしょうか。
あと、順番もレベル順に並び替えをお願いいたします。

**Comment by jacopen** [comment]
レベル順表示が未実装なので再オープン

**Comment by jacopen** [comment]
@miyamotoc ロゴについては全て透過にしたものを環境に反映済みです。
スポンサーレベル順表示に関して、ここの画面に関してはもう少し手入れが必要そうなので、今晩実装して明日朝までにはリリースします

**Comment by miyamotoc** [comment]
ロゴの変更誠にありがとうございます。
レベル順表示につきましてお手数をおかけいたします。
どうぞよろしくお願いいたします。
