### ISSUE TITLE
vimeo id が消える

### ISSUE THREAD

**Issue by scottmacdonald1** [cloudopsdays/dreamkast#87]
@jacopen 

確認までですが、入力されている動画のvimeoIDを昨日入れてものが今朝消えてたので、今朝また入れた再度消えました。
実装がアップデートされる度にvimeoのIDがすべて消えますでしょうか？これから配信開始しますので、今後の
アップデートの際、同様な現象があるようでしたら、先にアップデートのタイミングについて相談させてください。
60件のIDの再入力は少し手間ですので。。。

**Comment by jacopen** [comment]
なんと・・・
消えてしまうのは意図した挙動ではないです。ちょっと手元でも再現するか確認してみます。
その上で理由が判明したら修正しますね。お手数おかけしました

**Comment by scottmacdonald1** [comment]
先ほど判明したが、こちらでセッションデータのCSVを更新してアップする度にvimeoIDが消えるようです。
