### ISSUE TITLE
セッション画面でのFacebookリンクが「シェア」という文字になっててわかりづらい

### ISSUE THREAD

**Issue by shintaro1018** [cloudopsdays/dreamkast#88]
セッション動画の画面の右上にTwitterとFacebookへのリンクがありますが、Facebookのリンクが「シェア」と黒文字になっています。
黒文字ということもありわかりにくいので「facebook」くらいの文字列かアイコンに変更できるとわかりやすいと思います。
優先度は高くないです。
環境はMacでChrome, Firefoxいずれも同じでした。

<img width="888" alt="スクリーンショット 2021-07-14 11 41 48" src="https://user-images.githubusercontent.com/1232626/125552410-3d89ea0f-47f0-4d31-a1a3-e275119eec66.png">

**Comment by jacopen** [comment]
こちらは既知の問題でして、リロードするとFacebookアイコンが表示されます。
Facebook側から提供されているコードを使っているだけなのでこちらでコントロールが出来ないのですが、何故こうなってしまうのか原因が掴み切れていないところです。。。

https://github.com/cloudnativedaysjp/dreamkast/issues/468

**Comment by shintaro1018** [comment]
あー既存チケット見てませんでしたすみません。確かにリロードすると出ますね。

**Comment by jacopen** [comment]
自分もちょっと問題だなって思っていたので、何らしか解決方法模索してみたいと思います。issue再オープンしますね
