### ISSUE TITLE
ログイン画面のAuth0 development keys警告

### ISSUE THREAD

**Issue by scottmacdonald1** [cloudopsdays/dreamkast#89]
「動画を視聴する」をクリックしログインを求められる際、下記の警告が表示されます。実際の影響はわかりませんが、念のためメールにてお知らせします。

https://auth0.com/docs/connections/social/devkeys

    Alerts
    Dev Keys

    One or more of your connections are currently using Auth0 development keys and should not be used in production.

![Screenshot from 2021-07-14 13-04-07](https://user-images.githubusercontent.com/14048597/125563092-dd7845fb-52da-4cfc-a18e-2a81d4433eeb.png)
スクリーンショットを添付します。

**Comment by jacopen** [comment]
ありがとうございます、設定漏れが一つありましたので今晩対応します

**Comment by jacopen** [comment]
こちら解消しました
