### ISSUE TITLE
チャット機能

### ISSUE THREAD

**Issue by scottmacdonald1** [cloudopsdays/dreamkast#90]
確認までですが、配信期間は長いので、使用予定はなかったが、質問する手段を設けたいことになったため、CNDOの実装で見せていただいたDreamkastの独自チャット機能を生かすことは可能でしょうか？

**Comment by jacopen** [comment]
チャット機能はライブ配信画面(実装的には別UI)で実装しているものなので、今のオンデマンド配信画面に取り込むのはちょっと難しそうです。

8/27のライブ配信時では利用可能です
