### ISSUE TITLE
スポンサー追加（シルバー）

### ISSUE THREAD

**Issue by miyamotoc** [cloudopsdays/dreamkast#95]
急遽スポンサーが追加となりましたのでロゴを共有いたします。（シルバーなのでブースはなし）
よろしくお願いいたします。
![hpe_300x86_透過](https://user-images.githubusercontent.com/82624753/125720797-22d49276-21b8-4d07-bd3b-6a2203edf937.png)

日本ヒューレット・パッカード合同会社

**Comment by jacopen** [comment]
対応します
